version: "3.7"

services:
  clchat_postgres:
    image: postgres:15.1
    restart: on-failure
    env_file:
      - database.env
    ports:
      - 5432:5432
    volumes:
      - clchat_postgres_data:/var/lib/postgresql/data

  clchat_pgadmin:
    image: "dpage/pgadmin4:6.20"
    volumes:
      - clchat_pgadmin_data:/var/lib/pgadmin
    ports:
      - 5050:80
    restart: on-failure
    container_name: clchat_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=password

  clchat_redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - clchat_redis_data:/data
    restart: on-failure
    environment:
      - REDIS_REPLICATION_MODE=master

  clchat_redisinsight:
    image: redislabs/redisinsight:latest
    restart: on-failure
    ports:
      - "8001:8001"
    volumes:
      - clchat_redisinsight_data:/db

volumes:
  clchat_postgres_data:
    driver: local
  clchat_pgadmin_data:
    driver: local
  clchat_redis_data:
    driver: local
  clchat_redisinsight_data:
    driver: local

networks:
  default:
    driver: bridge
