version: "3.7"

services:
  clchat_postgres:
    image: postgres:15.1
    restart: on-failure
    env_file:
      - database.env
    ports:
      - 5432:5432

  clchat_redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - target: 6379
        published: 6380
        protocol: tcp
        mode: host
    restart: on-failure
    environment:
      - REDIS_REPLICATION_MODE=master

  clchat_app:
    image: clchat_app:latest
    restart: on-failure
    env_file:
      - app.env
    ports:
      - "8080:8080"

networks:
  default:
    driver: bridge
